name: Terminal Ubuntu Session

on:
  workflow_dispatch:  # یعنی دستی از تب Actions اجراش می‌کنی

jobs:
  terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # فقط خودت دسترسی داری، امن‌تره
